### ISSUE TITLE
Keep getting Error code: 401

### ISSUE THREAD

**Issue by gunawebs** [ben-aaron188/rgpt3#12]
When I do

`>   gpt3_authenticate("./access_key.txt")`

I get two rows in the output

```
[1] "Will use --> sk-xxxxxx for authentication."
[2] "Will use -->  for authentication."   
```      

And when I try and run the chatgpt function, I get this error:

`Request completed with error. Code: 401, message: You didn't provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY), or as the password field (with blank username) if you're accessing the API from your browser and are prompted for a username and password. You can obtain an API key from https://platform.openai.com/account/api-keys.`

I think somewhere it is setting the key to empty string.

**Comment by gunawebs** [comment]
Also, BTW, I am not able to run this

```
> gpt3_endsession()
Error in gpt3_endsession() : could not find function "gpt3_endsession"
```

**Comment by gunawebs** [comment]
Also unable to run this

```
> check_apikey_form()
Error in check_apikey_form() : 
  could not find function "check_apikey_form"
```

**Comment by gunawebs** [comment]
Note: Once I restarted rstudio a few times, it worked

**Comment by ben-aaron188** [comment]
OK thanks.
