### ISSUE TITLE
ChatGPT support

### ISSUE THREAD

**Issue by wptmdoorn** [ben-aaron188/rgpt3#4]
The ChatGPT API is out - would be very nice to have ChatGPT support :-)
https://openai.com/blog/introducing-chatgpt-and-whisper-apis 

I can help you contribute if needed!

**Comment by ben-aaron188** [comment]
Hi @wptmdoorn - Yes, absolutely. I've got this on my list. Will provide an updated version soon for the basic use of the ChatGPT model. The full conversational flow (back and forth between model and user) needs some more thought. Could be a separate package. More soon.

**Comment by ben-aaron188** [comment]
Just in case: there's a basic access point to ChatGPT in this R package: https://github.com/jcrodriguez1989/chatgpt
It doesn't work the way `rgpt3` works (so no bunch processing, etc.), but for simple things this should do.
I'll work on the ChatGPT support anyway though, so will keep you posted.

**Comment by ben-aaron188** [comment]
ChatGPT support is now live.

**Comment by wptmdoorn** [comment]
Very cool thanks, will definitely test!
