### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by isomemo** [ben-aaron188/rgpt3#9]
Install error using R 4.1.3

> devtools::install_github("ben-aaron188/rgpt3")
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘memoise’

**Comment by ben-aaron188** [comment]
Can you try to re-install devtools and run it again then with `devtools::install_github("ben-aaron188/rgpt3", force=T)`?
The `rgpt3` package doesn't use the `memoise` package, so I suspect this is a devtools thing.

**Comment by isomemo** [comment]
@ben-aaron188 yes, that fixed it!
